CREATE TABLE DEP(
    DEP_ID INT PRIMARY KEY,
    DEP_NAME VARCHAR(30)
);

CREATE TABLE STD(
    STD_ID INT PRIMARY KEY,
    STD_NAME VARCHAR(30),
    DEP INT,
    FOREIGN KEY (DEP) REFERENCES DEP(DEP_ID)
);


INSERT INTO DEP VALUES (1,'COMP');
INSERT INTO DEP VALUES (2,'IT');

INSERT INTO STD VALUES (1,'ERWIN',1);
INSERT INTO STD VALUES (2,'TOJI',2);
INSERT INTO STD VALUES (3,'GOJO',1);
INSERT INTO STD VALUES (4,'LEVI',1);

SELECT * FROM DEP;
SELECT * FROM STD;

SELECT DEP,FLOOR(AVG(STD_ID)) AS AVG_STD FROM STD GROUP BY DEP HAVING DEP=1;

SELECT COUNT(*) AS TOTAL_STUDENTS FROM STD;



CREATE TABLE STD2 (
    STD_ID INT PRIMARY KEY,
    STD_NAME VARCHAR(30),
    DEP INT,
    FOREIGN KEY (DEP) REFERENCES DEP(DEP_ID)
);

INSERT INTO STD2 VALUES (1,'SASUKE',1);
INSERT INTO STD2 VALUES (2,'TOJI',2);
INSERT INTO STD2 VALUES (3,'EREN',2);
INSERT INTO STD2 VALUES (4,'LEVI',2);

SELECT STD_NAME,DEP FROM STD2 WHERE DEP=2
UNION ALL
SELECT STD_NAME,DEP FROM STD WHERE DEP=1;

SELECT STD2.STD_NAME,STD.DEP 
FROM STD 
JOIN STD2
ON STD2.STD_NAME=STD.STD_NAME;

SELECT STD2.STD_NAME,STD.DEP 
FROM STD 
INNER JOIN STD2
ON STD2.STD_NAME=STD.STD_NAME;

SELECT STD2.STD_NAME,STD.DEP 
FROM STD 
LEFT JOIN STD2
ON STD2.STD_NAME=STD.STD_NAME;

SELECT STD2.STD_NAME,STD.DEP 
FROM STD 
RIGHT JOIN STD2
ON STD2.STD_NAME=STD.STD_NAME;





