-- 1. Create Parent Table
CREATE TABLE DEPARTMENT(
  DEP_ID INT PRIMARY KEY,
  DEP_NAME VARCHAR(30)
);

-- 2. Create STUDENT Table
CREATE TABLE STUDENT(
  STD_ID INT PRIMARY KEY,
  NAME VARCHAR(30),
  STD_DEP INT,
  MOB_NO BIGINT
);

-- 3. Create TEACHER Table
CREATE TABLE TEACHER(
  T_ID INT PRIMARY KEY,
  NAME VARCHAR(30),
  DEP INT
);

-- 4. Add constraints
ALTER TABLE STUDENT ADD CONSTRAINT fk_student_dep
FOREIGN KEY (STD_DEP) REFERENCES DEPARTMENT(DEP_ID);

ALTER TABLE TEACHER ADD CONSTRAINT fk_teacher_dep
FOREIGN KEY (DEP) REFERENCES DEPARTMENT(DEP_ID);

ALTER TABLE STUDENT ADD CONSTRAINT chk_mob CHECK (MOB_NO > 0);
ALTER TABLE STUDENT ADD CONSTRAINT unique_mob UNIQUE (MOB_NO);

-- 5. Insert values into DEPARTMENT (Parent table first)
INSERT ALL
  INTO DEPARTMENT (DEP_ID, DEP_NAME) VALUES (1,'CO')
  INTO DEPARTMENT (DEP_ID, DEP_NAME) VALUES (2,'IT')
  INTO DEPARTMENT (DEP_ID, DEP_NAME) VALUES (3,'EL')
  INTO DEPARTMENT (DEP_ID, DEP_NAME) VALUES (4,'EJ')
  
SELECT * FROM dual;

INSERT INTO DEPARTMENT VALUES (5,'AM');
-- 6. Insert values into STUDENT (Child table)
INSERT INTO STUDENT (STD_ID, NAME, STD_DEP, MOB_NO) VALUES (1,'REHAN',2,1234567890);
INSERT INTO STUDENT (STD_ID, NAME, STD_DEP, MOB_NO) VALUES (2,'ERWEN',1,1234567891);
INSERT INTO STUDENT (STD_ID, NAME, STD_DEP, MOB_NO) VALUES (3,'LEVI',4,1234567892);
INSERT INTO STUDENT (STD_ID, NAME, STD_DEP, MOB_NO) VALUES (4,'NARUTO',3,1234567893);



-- 7. Insert values into TEACHER
INSERT INTO TEACHER (T_ID, NAME, DEP) VALUES (1,'PROF_A',2);
INSERT INTO TEACHER (T_ID, NAME, DEP) VALUES (2,'PROF_B',3);
INSERT INTO TEACHER (T_ID, NAME, DEP) VALUES (3,'PROF_c',2);
INSERT INTO TEACHER (T_ID, NAME, DEP) VALUES (4,'PROF_d',3);


-- 8. Optional: Create & rename table
CREATE TABLE REHAN(R_ID INT, R_NAME VARCHAR(30));
RENAME REHAN TO KHALID;
DROP TABLE KHALID;

-- 9. Verify
SELECT * FROM DEPARTMENT;
SELECT * FROM STUDENT;
SELECT * FROM TEACHER;

SELECT NAME FROM STUDENT;//to select only one column 
SELECT NAME,MOB_NO FROM STUDENT;//to select multiple cols
SELECT NAME FROM TEACHER WHERE DEP=3;//selct based on condition

UPDATE TEACHER SET NAME='REHAN' WHERE DEP=2;//update from condition 
SELECT DISTINCT NAME FROM TEACHER;//remove duplicates without affecting orignal cols

SELECT * FROM STUDENT ORDER BY NAME;//orderwise sort 
SELECT * FROM STUDENT ORDER BY NAME DESC;//descorder sort 

SELECT NAME,DEP FROM TEACHER WHERE T_ID BETWEEN 1 AND 3 ORDER BY NAME ;

SELECT NAME,DEP FROM TEACHER WHERE NAME LIKE '%HAN%';

CREATE TABLE 






